# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - hadda-erp-v2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Create deployment package (exclude node_modules)
        run: |
          zip -r node-app.zip . \
            -x "node_modules/*" \
            -x "backend/node_modules/*" \
            -x "frontend/node_modules/*" \
            -x "**/node_modules/*" \
            -x ".git/*" \
            -x ".github/*" \
            -x "*.log" \
            -x "logs/*" \
            -x "backups/*" \
            -x "backend/backups/*" \
            -x "coverage/*" \
            -x "test_*.js" \
            -x "test-*.js" \
            -x "*.xml" \
            -x "*.csv" \
            -x "docs/*" \
            -x ".vscode/*" \
            -x ".idea/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: node-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Unzip artifact for deployment
        run: unzip node-app.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6C6A6652B52F4A41970FE5095C34F122 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A6301767893F4AA8854C986A10B54054 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_27C4040771C34FD29133F558562EDE9B }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hadda-erp-v2'
          slot-name: 'Production'
          package: .
          clean: true
          